"use strict";
const crypto=require("node:crypto"),fs=require("node:fs"),os=require("node:os"),path=require("node:path");
const {spawn}=require("node:child_process");
function vaultRoot(app){const root=app?.vault?.adapter?.getBasePath?.()||app?.vault?.adapter?.basePath;if(!root)throw new Error("Obsidian vault adapter does not expose its base path");return path.resolve(root);}
function autoscribeRoot(app){if(process.env.AUTOSCRIBE_ROOT)return path.resolve(process.env.AUTOSCRIBE_ROOT);return path.resolve(fs.realpathSync(path.join(vaultRoot(app),"_control")),"../../../..");}
function serviceCommand(app){const root=autoscribeRoot(app),explicit=process.env.AUTOSCRIBE_SERVICE_BIN,release=path.join(root,"platform/service/target/release/autoscribe-service"),debug=path.join(root,"platform/service/target/debug/autoscribe-service");if(explicit)return{command:explicit,prefix:[]};if(fs.existsSync(release))return{command:release,prefix:[]};if(fs.existsSync(debug))return{command:debug,prefix:[]};const cargo=path.join(os.homedir(),".cargo/bin/cargo");return{command:fs.existsSync(cargo)?cargo:"cargo",prefix:["run","--quiet","--manifest-path",path.join(root,"platform/service/Cargo.toml"),"--bin","autoscribe-service","--"]};}
function run(command,args,{cwd,input=""}={}){return new Promise((resolve,reject)=>{const child=spawn(command,args,{cwd,env:process.env,shell:false,stdio:["pipe","pipe","pipe"]});let stdout="",stderr="";child.stdout.on("data",c=>stdout+=c);child.stderr.on("data",c=>stderr+=c);child.once("error",reject);child.once("close",status=>status===0?resolve({stdout,stderr}):reject(new Error((stderr||stdout||`exit status ${status}`).trim())));child.stdin.end(input);});}
async function convertOne(app,relativePath){const root=vaultRoot(app),source=path.resolve(root,relativePath);if(path.relative(root,source).startsWith(".."))throw new Error(`Dispatch path is outside vault: ${relativePath}`);const filter=path.join(autoscribeRoot(app),"platform/pandoc/filters/emit/emit_ndjson.lua"),pandoc=process.env.PANDOC_BIN||"/usr/bin/pandoc";const result=await run(pandoc,[source,"--from=markdown+yaml_metadata_block+fenced_divs",`--lua-filter=${filter}`,"--to=native","--output=/dev/null"],{cwd:root});const line=result.stdout.split(/\r?\n/).find(v=>v.trim().startsWith("{"));if(!line)throw new Error(`Pandoc emitted no NDJSON record for ${relativePath}`);const record=JSON.parse(line),slug=String(record.record_identity||"").trim();if(!slug)throw new Error(`Pandoc record is missing record_identity: ${relativePath}`);return{relativePath,slug,record};}
function canonicalPayload(converted,plan){const calls=converted.map(({relativePath,slug,record})=>({type:"call",identity:slug,content:String(record.payload?.content||""),extra:{filename_hint:path.basename(relativePath),source_path:relativePath,metadata:Object.fromEntries(Object.entries(record.payload||{}).filter(([key])=>key!=="content"))}}));const enqueue=converted.map(({slug,record})=>{const row={call:slug,plan};if(typeof record.directive==="string"&&record.directive.trim())row.directive=record.directive.trim();return row;});return JSON.stringify({version:1,calls,enqueue})+"\n";}
async function prepareDispatch(app,{paths,plan,planVersion,message}){const root=vaultRoot(app),selected=[...new Set(paths.map(String))].sort();if(!selected.length)throw new Error("Dispatch requires selected files");const converted=await Promise.all(selected.map(p=>convertOne(app,p))),payload=canonicalPayload(converted,plan),dispatch=`run-${crypto.randomUUID()}`;const request={version:1,database_path:process.env.AUTOSCRIBE_DATABASE||path.join(os.homedir(),".local/share/autoscribe/service.sqlite"),repository_path:root,dispatch,plan,plan_version:String(planVersion||plan),records:converted.map(({relativePath,slug})=>({slug,path:relativePath})),payload,payload_sha256:crypto.createHash("sha256").update(payload).digest("hex"),commit_message:String(message||"").trim()||`DISPATCH SOURCE ${plan}: ${dispatch}`};const executable=serviceCommand(app),response=await run(executable.command,[...executable.prefix,"dispatch-prepare"],{cwd:root,input:JSON.stringify(request)}),output=JSON.parse(response.stdout.trim()||"{}");if(!output.ok)throw new Error(output.error||"Rust dispatch preparation failed");return{...output,count:converted.length};}
module.exports={canonicalPayload,prepareDispatch};
