"""
asc.core.identity
================

Canonical identity utilities for asc.

This module defines:
- ULID generation
- ULID parsing and validation (for ingestion use)
- Ordered ULID collection serialization

Design principles
-----------------
- Identity is explicit and stable.
- Redis is a string-only persistence substrate.
- Order is preserved by position, never by encoding tricks.
- Validation of *external* ULIDs happens at ingestion boundaries.
- After ingestion, all ULIDs are trusted.
"""

from typing import List, Optional
import ulid 
from typing_extensions import Annotated
from pydantic import BeforeValidator


# ---------------------------------------------------------------------------
# ULID basics
# ---------------------------------------------------------------------------

ULID_LEN = 26
ULID_DELIM = "|"


def generate_identity() -> str:
    """Generate a new ULID string.

    This is the only place ULIDs are created inside the pipeline.
    All ULIDs produced here are assumed valid everywhere else.
    """
    return str(ulid.ULID())


# ---------------------------------------------------------------------------
# ULID validation (ingestion boundary)
# ---------------------------------------------------------------------------


def validate_ulid(
    value: str,
    *,
    info_only: bool = True,
    now_ms: Optional[int] = None,
) -> None:
    if not isinstance(value, str):
        raise ValueError(f"ULID must be a string, got {type(value)!r}")

    try:
        ulid_obj = ulid.ULID.from_str(value)
    except Exception as exc:
        raise ValueError(f"Invalid ULID {value!r}") from exc

    # ts_ms = ulid_obj.timestamp
    # now = now_ms if now_ms is not None else int(time.time() * 1000)
    # age_ms = now - ts_ms

    # if info_only:
    #     if age_ms < 0:
    #         print(f"INFO: ULID {value} has a future timestamp")
    #     else:
    #         age_days = age_ms // (1000 * 60 * 60 * 24)
    #         if age_days > 0:
    #             print(f"INFO: ULID {value} was generated {age_days} days ago")




# ---------------------------------------------------------------------------
# Ordered ULID collections (transport only)
# ---------------------------------------------------------------------------


def join_ulids(ulids: List[str]) -> str:
    """
    Serialize an ordered list of ULIDs into a single Redis-safe string.

    Rules
    -----
    - Order is preserved exactly as given
    - Empty list -> empty string
    - No validation is performed here

    This function is *transport only* and assumes ULIDs are already valid.
    """
    if not ulids:
        return ""
    return ULID_DELIM.join(ulids)


def split_ulids(value: str) -> List[str]:
    """
    Deserialize an ordered ULID string back into a list.

    Rules
    -----
    - Empty string -> empty list
    - Order is preserved
    - No validation is performed here

    Validation belongs exclusively at ingestion boundaries.
    """
    if not value:
        return []
    return value.split(ULID_DELIM)

# ---------------------------------------------------------------------------
# ULID provenance policies (Pydantic v2)
# ---------------------------------------------------------------------------



def _internal_ulid(value):
    """
    Accept internally supplied ULIDs or None.

    Rules:
    - None → ULID will be generated by the model
    - str  → trusted internal ULID (rehydration, pipeline use)
    - anything else → error
    """
    if value is None:
        return value

    if not isinstance(value, str):
        raise ValueError(
            f"Internal ULID must be a string or None, got {type(value)!r}"
        )

    return value



def _require_valid_ulid(value):
    """
    Require and validate an externally supplied ULID.

    Intended for ingestion-boundary models (calls, sysmessages, etc.).
    """
    if value is None:
        raise ValueError("ULID is required")

    # Structural validation only; informational timestamp checks are allowed
    validate_ulid(value, info_only=True)
    return value


# ---------------------------------------------------------------------------
# Public identity annotations
# ---------------------------------------------------------------------------

InternalULID = Annotated[
    Optional[str],
    BeforeValidator(_internal_ulid),
]

"""
ULID policy for internally generated identities.

Rules:
- ULID must NOT be supplied by the caller
- ULID is generated post-init by the model
"""

ExternalULID = Annotated[
    str,
    BeforeValidator(_require_valid_ulid),
]
"""
ULID policy for externally supplied identities.

Rules:
- ULID MUST be supplied by the caller
- ULID is structurally validated at ingestion time
"""
